Initial view
CoderDojo/coderdojo.com pull request #92
Opened 2021-07-12 12:30 UTC by magdalenajadach

2021-07-12 13:14 UTC, DanielBrierton commented
:heavy_check_mark: Deploy Preview for *cdf-website* ready!


:hammer: Explore the source changes: 8099f761837dd22c7cf3f56ed4898c89661423f9

:mag: Inspect the deploy log: [https://app.netlify.com/sites/cdf-website/deploys/60ec3fbc5322f80007faa6bd](https://app.netlify.com/sites/cdf-website/deploys/60ec3fbc5322f80007faa6bd?utm_source=github&utm_campaign=bot_dl)

:sunglasses: Browse the preview: [https://deploy-preview-92--cdf-website.netlify.app](https://deploy-preview-92--cdf-website.netlify.app?utm_source=github&utm_campaign=bot_dp)

2021-07-12 14:06 UTC, glenpike requested changes
Just needs a fix for square image.

2021-07-12 14:06 UTC, glenpike commented on components/index/Birthday.vue
> +
Image is stretched to a square in the preview.  Maybe adding `align-self: center;` on .c-birthday__photo will fix - behaves in browser and doesn't affect in responsive view.

2021-07-12 14:06 UTC, glenpike commented on assets/_variables.scss
> +$foam: #D1FAFD;
For consistency, this should possibly be '$cd-foam', but don't know why we prefix the colours anyway - it's a minor thing and doesn't need fixing unless you want to start doing all of the other things that need fixing too :)

2021-07-13 10:23 UTC, glenpike approved these changes
LGTM

2021-07-23 08:06 UTC, merged